name: sup_gen_repository

packages:
  - apps/**
  - packages/**




scripts:
  analyze:
    exec: dart analyze .
  gen:build_runner:
    exec: dart run build_runner build --delete-conflicting-outputs
    packageFilters:
      # ignore:
      #   - example
      #   - example_resources
      dependsOn: build_runner
    description: dart run build_runner build --delete-conflicting-outputs
  get:
    run: flutter pub get
    exec:
      concurrency: 2
    description: flutter pub get
