name: sup_gen
description: A starting point for Dart libraries or applications.
homepage: https://github.com/woueziou/sup_gen.git
repository: https://github.com/woueziou/sup_gen.git
documentation: https://github.com/woueziou/sup_gen.git
issue_tracker: https://github.com/woueziou/sup_gen/issues
version: 1.1.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.0

# Add regular dependencies here.

dev_dependencies:
  melos: ^7.1.0
