targets:
  $default:
    builders:
      sup_gen_runner:
        enabled: true

builders:

  sup_gen_runner:
    import: 'package:sup_gen_runner/sup_gen_runner.dart'
    builder_factories: ['build']
    build_extensions: { '$package$': [] }
    auto_apply: root_package
    build_to: source
    runs_before:
      - "json_serializable|json_serializable" # Run before the JsonSerializable generator
      - "freezed|freezed" # Run before the Freezed generator
    
